### ISSUE TITLE
getMotionDetectConfig - Ongeldig antwoord van netwerkapparaat gekregen

### ISSUE THREAD

**Issue by Veldkornet** [edwinvdpol/com.foscam#10]
**Describe the issue**
After adding the devices, they initially show a red "!" icon, although that does disappear after a while. Looking in the logs, you see the below.

**Expected behavior**
No errors

**CGI result**
```
<CGI_Result>
    <result>-3</result>
</CGI_Result>
```

**More information**
- Homey firmware version: 2.1.1
- App version: 2.0.0
- Camera model: FI9900EP, FI9900EPV5

**Additional context**
```
(node:10638) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
(node:10638) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13) 
(node:10638) UnhandledPromiseRejectionWarning: Error: Configureer uw SMTP-instellingen. at Mail.send (/lib/Mail.js:24:19) at Homey.app.getSnapshot.then.result (/lib/Device.js:308:32) at at process._tickCallback (internal/process/next_tick.js:189:7) 
✓ Back taking snapshot
─────────────────────────────────
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP+V5 
Command : getMotionDetectConfig 
URL : http://10.20.30.12:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Carport set motion command to `1` 
─────────────────────────────────
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP+V5 
Command : getMotionDetectConfig 
URL : http://10.20.30.12:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Carport initiated 
✓ Found device: Carport (FI9900EP+V5) 
✓ Searching device 
✓ Pairing started 
─────────────────────────────────
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP 
Command : getMotionDetectConfig 
URL : http://10.20.30.10:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Front set motion command to `1` 
─────────────────────────────────
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP 
Command : getMotionDetectConfig 
URL : http://10.20.30.10:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Front initiated 
✓ Found device: Front (FI9900EP) 
✓ Searching device 
✓ Pairing started 
─────────────────────────────────
───────────── ERROR ───────────── 
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP 
Command : getMotionDetectConfig 
URL : http://10.20.30.11:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Back set motion command to `1` 
─────────────────────────────────
Error: Ongeldig antwoord van netwerkapparaat gekregen. at Api._processData (/lib/Api.js:143:19) at Api._httpResponse (/lib/Api.js:129:25) at httpPromise.then.result (/lib/Api.js:104:29) at at process._tickCallback (internal/process/next_tick.js:189:7) 
Params : {"cmd":"getMotionDetectConfig","usr":"NewUser","pwd":"****"}
Message : Ongeldig antwoord van netwerkapparaat gekregen. 
Model : FI9900EP 
Command : getMotionDetectConfig 
URL : http://10.20.30.11:88/cgi-bin/CGIProxy.fcgi 
───────────── ERROR ───────────── 
✓ Back initiated 
✓ Found device: Back (FI9900EP) 
✓ Searching device 
─────────────────────────────────

```

**Comment by edwinvdpol** [comment]
These errors are correct. It checks the motion config command first. These errors will only show 1 time per camera. The last one says you have to enter all details on the settings page.

**Comment by Veldkornet** [comment]
Oh okay. What if I don't want emails? I use the image tokens.

I see there is an option "stuur e-mail na snapshot" which is set to true by default.
But if I want to set it to false, it wants me to fill in all the settings.

Off topic, I see the memory usage is (at least initially) much better. Was that an improvement in 2.0?

**Comment by edwinvdpol** [comment]
> I see there is an option "stuur e-mail na snapshot" which is set to true by default.
> But if I want to set it to false, it wants me to fill in all the settings.

If this is the case, then this is a bug. Thank you reporting. I will fix this asap in the next _beta_ version.

> Off topic, I see the memory usage is (at least initially) much better. Was that an improvement in 2.0?

I made a lot of code optimalisations and reduced the package size drastically by rewriting most of the code. The fact is, that Homey / NodeJS does not handle HTTP requests the most efficient way. It has proven, that over time the memory of apps will rise if it has many requests. I made the motion detect function, but I removed it afterwards after a week for this specific reason. After a few days, memory kept building up. A few people asked for it, it was possible, but a more stable app with less memory usage has my priority.

**Comment by edwinvdpol** [comment]
Todo @edwinvdpol v2.0:

- [ ] Check and fix SMTP settings bug when no snapshot is send afterwards.
- [ ] Remove initial error (determine motion command) to prevent "false" errors.

**Comment by Veldkornet** [comment]
Cool, my Homey approves of your updates ;)

![image](https://user-images.githubusercontent.com/10297361/56666510-57812400-66ac-11e9-9cbf-90246652d884.png)

Perhaps the "stuur e-mail na snapshot" should be set to false by default until the user fills out the server info?

Anyway, thanks for the quick response.

**Comment by edwinvdpol** [comment]
Ow nice, looking good!! I set this value default to 'true' because v1.0 only supported the e-mail feature. So actually only for backwards compatibility reasons really. Good point!

**Comment by edwinvdpol** [comment]
New beta version is submitted at the Athom app store! Waiting for approval.
